server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://mysql_boot:3306/springweb
    username: ssu
    password: 1234
#    minimum-idle: 1
#    maximum-pool-size: 2
#    pool-name: master
  jpa:
    properties:
      hibernate:
        dialect: me.ssu.querydslspringrestapi.config.jpa.MySQLDialect

logging:
  level:
    root: info
    me:
      ssu:
        qeurydslspringrestapi: debug
#      amazonaws:
#        internal:
#          InstanceMetadataServiceResourceFetcher: error
#        util:
#          EC2MetadataUtils: error
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: off
        SQL: off
      springframework:
        data:
          redis: trace
          mongodb:
            core:
              MongoTemplate: debug
        boot:
          autoconfigure: error

#feign-client-config
feign:
  client:
    config:
      default:
        loggerLevel: FULL
#NONE : 로깅하지 않습니다. (DEFAULT)
#BASIC : Request Method와 URL 그리고 Reponse 상태 코드와 실행 시간을 로깅합니다.
#HEADERS : Request, Response Header 정보와 함께 BASIC 정보를 로깅합니다.
#FULL : Request와 Response의 Header, Body 그리고 메타데이터를 로깅합니다.

#external-api
external-api:
  push: 'http://localhost:8081'

#springdoc-api-docs
springdoc:
  api-docs:
    enabled: true